Review tag component
Smelser-Squad/Nile pull request #111
Opened 2021-04-16 19:28 UTC by kpugh97

2021-04-16 19:32 UTC, zmiles17 requested changes

2021-04-16 19:32 UTC, zmiles17 commented on nile-backend/src/main/java/com/tp/Nile/controllers/ReviewController.java
> +    @PostMapping("/addReview")
Please just leave this as @PostMapping and I'm going to say the same thing for every other route where it's unnecessary.

2021-04-16 19:32 UTC, zmiles17 commented on nile-backend/src/main/resources/application-dev.properties
> +<<<<<<< HEAD
Left over merge conflict please clean it up.

2021-04-16 19:44 UTC, wcollins37 approved these changes

2021-04-19 14:23 UTC, wcollins37 approved these changes

2021-04-20 14:34 UTC, closed without merging