Syncing and added Vendor Model
Smelser-Squad/Nile pull request #48
Opened 2021-04-13 21:20 UTC by tamera-brown

2021-04-13 21:23 UTC, wcollins37 approved these changes

2021-04-14 01:26 UTC, wcollins37 approved these changes

2021-04-14 03:55 UTC, noel-castillo requested changes
I don't think feature needs orders as one of its properties. Everything else looks solid.

2021-04-14 12:18 UTC, noel-castillo approved these changes

2021-04-14 13:36 UTC, closed without merging